[tool]
[tool.poetry]
name = "cleaners"
version = "2022.9.1"
homepage = "https://github.com/ScottMGustafson/cleaners"
description = "Data cleaners for DS projects in the scikit-learn pipeline format."
authors = ["scott gustafson <s1gustaf@gmail.com>"]
readme = "README.md"
packages = [
    { include = "cleaners" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pandas = "^1.4.3"
dask = "^2022.9.1"
scikit-learn = "^1.1.2"


[tool.poetry.extras]
test = [
    "pytest",
    "black",
    "nb_black",
    "isort",
    "mypy",
    "types-PyYaml",
    "flake8",
    "flake8-docstrings",
    "pytest-cov",
    "coverage"
]

dev = ["tox", "pre-commit", "virtualenv", "pip", "twine", "toml", "bump2version", "ipykernel", "jupyter", "jupyterlab-code-formatter"]

doc = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocs-material-extensions",
    "mkdocs-autorefs"
]

[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
